<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    use HasFactory;

    public function delete()
    {
        @unlink(storage_path('app/public/branches/' . $this->image));
        return parent::delete(); // TODO: Change the autogenerated stub
    }

}
