<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    use HasFactory;

    public function delete()
    {
        @unlink(storage_path('app/public/members/' . $this->image));
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
